@url_base = http://localhost:8000
@register = {{url_base}}/auth/register
@login = {{url_base}}/auth/login
@alumno = {{url_base}}/alumnos


###
DELETE {{alumno}}/1

###
POST {{alumno}}/
Content-Type: application/json

{
    "nombre": "Carla Perez",
    "dni": "1234567",
    "email": "cperez@example.com",
    "ciudad": "Buenos Aires",
    "edad": 18
}
###
POST {{login}}
Content-Type: application/json

{
    "email": "ejemplo@danza.com",
    "password": "danza123"
}



###
POST {{register}}
Content-Type: application/json

{
    "email": "ejemplo@danza.com",
    "nombre": "Lola Castro",
    "password": "danza123"
}



